"""add_credit_card_payment_account

Revision ID: e349329765d1
Revises: 0003
Create Date: 2026-05-03 22:45:48.377681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e349329765d1'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_cards', sa.Column('payment_account_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'credit_cards', 'accounts', ['payment_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'credit_cards', type_='foreignkey')
    op.drop_column('credit_cards', 'payment_account_id')
    # ### end Alembic commands ###
