"""Add end_date to transactions

Revision ID: 16a2a7915204
Revises: e349329765d1
Create Date: 2026-05-04 00:28:28.668072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16a2a7915204'
down_revision: Union[str, None] = 'e349329765d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'end_date')
    # ### end Alembic commands ###
