"""Add parent_id to transactions for recurring occurrences

Revision ID: 959b4e9245a7
Revises: 202607260002
Create Date: 2026-08-16 21:49:19.955066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '959b4e9245a7'
down_revision: Union[str, None] = '202607260002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'transactions', ['parent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'parent_id')
    # ### end Alembic commands ###
